### ISSUE TITLE
macOS Sierra v10.12.6 not working

### ISSUE THREAD

**Issue by Bulletz4mysa** [obsidianproject/Obsidian-Qt#1]
Process:               Obsidian-Qt [3838]
Path:                  /Users/USER/Desktop/Obsidian-Qt.app/Contents/MacOS/Obsidian-Qt
Identifier:            co.obsidian.Obsidian-Qt
Version:               0
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Obsidian-Qt [3838]
User ID:               501

Date/Time:             2017-08-30 11:17:48.199 -0700
OS Version:            Mac OS X 10.12.6 (16G29)
Report Version:        12
Anonymous UUID:        29627D60-A8E6-D211-D575-4C75431E0818

Sleep/Wake UUID:       2426F0FA-F568-4CB4-BA13-FCC7AD53233E

Time Awake Since Boot: 67000 seconds
Time Since Wake:       3200 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: /opt/local/lib/libminiupnpc.16.dylib
  Referenced from: /Users/USER/Desktop/Obsidian-Qt.app/Contents/MacOS/Obsidian-Qt
  Reason: image not found

Binary Images:
       0x1009bc000 -        0x100f4fff3 +co.obsidian.Obsidian-Qt (0) <B45DAE48-2BED-304D-BBC1-25B052ECBAFD> /Users/USER/Desktop/Obsidian-Qt.app/Contents/MacOS/Obsidian-Qt
       0x109daa000 -        0x109de7dc7  dyld (433.5) <322C06B7-8878-311D-888C-C8FD2CA96FF3> /usr/lib/dyld

Model: MacBookPro14,3, BootROM MBP143.0160.B02, 4 processors, Intel Core i7, 3.1 GHz, 16 GB, SMC 2.45f0
Graphics: kHW_IntelHDGraphics630Item, Intel HD Graphics 630, Built-In
Graphics: kHW_AMDRadeonPro560Item, Radeon Pro 560, PCIe, 4096 MB
Memory Module: BANK 0/DIMM0, 8 GB, LPDDR3, 2133 MHz, 0x802C, 0x4D5435324C31473332443450472D30393320
Memory Module: BANK 1/DIMM0, 8 GB, LPDDR3, 2133 MHz, 0x802C, 0x4D5435324C31473332443450472D30393320
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x173), Broadcom BCM43xx 1.0 (7.21.171.130.1a1)
Bluetooth: Version 5.0.5f1, 3 services, 27 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
USB Device: USB 3.0 Bus
USB Device: iBridge
Thunderbolt Bus: MacBook Pro, Apple Inc., 22.2
Thunderbolt Bus: MacBook Pro, Apple Inc., 22.2

**Comment by Doken-Tokuyama** [comment]
Process:               Obsidian-Qt [2251]
Path:                  /Volumes/VOLUME/*/Obsidian-Qt.app/Contents/MacOS/Obsidian-Qt
Identifier:            co.obsidian.Obsidian-Qt
Version:               0
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Obsidian-Qt [2251]
User ID:               501

Date/Time:             2017-08-30 19:39:43.354 +0200
OS Version:            Mac OS X 10.12.6 (16G29)
Report Version:        12
Anonymous UUID:        57F4F865-3876-7A39-61FB-D264EA310F52

Sleep/Wake UUID:       4EEB9F66-F236-4073-8236-B59FC1E4F170

Time Awake Since Boot: 34000 seconds

System Integrity Protection: enabled

Notes:                 Translocated Process

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: /opt/local/lib/libssl.1.0.0.dylib
  Referenced from: /Volumes/VOLUME/*/Obsidian-Qt.app/Contents/MacOS/Obsidian-Qt
  Reason: image not found

Binary Images:
       0x1039b2000 -        0x103f45ff3 +co.obsidian.Obsidian-Qt (0) <B45DAE48-2BED-304D-BBC1-25B052ECBAFD> /var/folders/*/Obsidian-Qt.app/Contents/MacOS/Obsidian-Qt
       0x104184000 -        0x10418cff3 +libminiupnpc.16.dylib (0) <C0328337-BDDE-37CA-9D40-BA304D48EE87> /usr/local/lib/libminiupnpc.16.dylib
       0x111b69000 -        0x111ba6dc7  dyld (433.5) <322C06B7-8878-311D-888C-C8FD2CA96FF3> /usr/lib/dyld
    0x7fff72f64000 -     0x7fff73d3dff3  com.apple.AppKit (6.9 - 1504.83.101) <AE51ACB3-D501-3F91-B369-3D3711F24D0A> /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
    0x7fff73d4f000 -     0x7fff73d4ffff  com.apple.ApplicationServices (48 - 48) <DA687F9A-7B2D-342B-8796-16E45344F853> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/ApplicationServices
    0x7fff76ea2000 -     0x7fff77248fff  com.apple.Foundation (6.9 - 1349.91) <A37CB4EC-0730-3DD6-9358-60491BF40EF2> /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation

Model: iMac14,4, BootROM IM144.0179.B31, 2 processors, Intel Core i5, 1,4 GHz, 8 GB, SMC 2.21f92
Graphics: Intel HD Graphics 5000, Intel HD Graphics 5000, Built-In
Memory Module: BANK 0/DIMM0, 4 GB, DDR3, 1600 MHz, 0x80AD, 0x483943434E4E4E424C54414C41522D4E5444
Memory Module: BANK 1/DIMM0, 4 GB, DDR3, 1600 MHz, 0x80AD, 0x483943434E4E4E424C54414C41522D4E5444
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x111), Broadcom BCM43xx 1.0 (7.21.171.130.1a1)
Bluetooth: Version 5.0.5f1, 3 services, 27 devices, 1 incoming serial ports
Network Service: Ethernet, Ethernet, en0
Network Service: Wi-Fi, AirPort, en1
Serial ATA Device: APPLE HDD HTS545050A7E362, 500,11 GB
USB Device: USB 3.0 Bus
USB Device: My Passport 0820
USB Device: asm1351
USB Device: BRCM20702 Hub
USB Device: Bluetooth USB Host Controller
USB Device: FaceTime HD Camera (Built-in)
USB Device: USB Hub 2.0
Thunderbolt Bus: iMac, Apple Inc., 30.8

**Comment by RhythmScout** [comment]
Same here with
`Termination Reason:    DYLD, [0x1] Library missing`
