### ISSUE TITLE
My wallet won't open. Have transferred the ODN to it, bit now I only get the error message

### ISSUE THREAD

**Issue by leehills747** [obsidianproject/Obsidian-Qt#42]
<img width="1280" alt="screen shot 2017-10-03 at 20 17 15" src="https://user-images.githubusercontent.com/32496231/31144442-a7de0baa-a878-11e7-92cd-36fae1cd2774.png">

**Comment by netsfx** [comment]
why did it work before? what did you change?

**Comment by leehills747** [comment]
Hi, absolutely nothing changed. I downloaded it, opened it, got the address and withdrew from the website, then when I tried to open it again it comes up with that error message.

**Comment by petermcclory** [comment]
@leehills747 can you check that macOS is completely up to date with the latest free OS updates? This is a common fix for similar issues to what you are displaying. If that fixes it, please report back!

**Comment by leehills747** [comment]
Hi @petermcclory All updated and no fix unfortunately.

**Comment by netsfx** [comment]
so, it worked an then it stopped working???

**Comment by leehills747** [comment]
Indeed - just comes up with the cannot be opened message above

**Comment by leehills747** [comment]
Is anyone from the Obsidian team going to resolve this??

**Comment by Manbearpixel** [comment]
Hey @leehills747 ! Sorry you are still having trouble. It seems a library file has gone missing so the only thing I can recommend at this point is to reinstall the Obsidian-QT wallet completely!

Before doing so, please **backup your wallet.dat** file located in your ObsidianQT Application Support folder. You'll find that location by opening up your Finder application, and pressing `CMD+SHIFT+G` and entering: `~/Library/Application Support/`. There you can copy and paste your `wallet.dat` file somewhere safe like in your Desktop for now. You can also for safety, copy the entire ObsidiandQT folder somewhere else for now.

Alternatively you can run this in your `Terminal` application which will copy the file to your Desktop.
```
sudo cp ~/Library/Application\ Support/ObsidianQt/wallet.dat ~/Desktop/wallet.dat
```

After you have backed up your wallet you should remove the Application Support folder, and remove the Obsidian-QT Application. You can run the command below in your `Terminal` Application.
**Only run this command after you have backed up your wallet.dat -- Final Warning!**
```
sudo rm -R ~/Library/Application\ Support/ObsidianQt
```

This removes the support folder. Finally, you will need to remove the Obsidian-QT application, you can do that by just dragging and dropping the application from your `/Applications` folder into your Trash.

Now re-download the Obsidian-QT Mac OS application and re-install from scratch. After you start Obsidian-QT it will generate a new `wallet.dat` file for you and begin downloading the blockchain again. You can close the application now, and remove the generated `wallet.dat` with your backup, and then start the application again. Please understand it will take some time to catch up with the network since you removed the original folder.

Let me know if you have more questions!

**Comment by Manbearpixel** [comment]
@leehills747 Any chance you have been successful in resolving this? We'll be closing this issue soon if there's no update from you in a few days.
